# Generated by Django 3.1.3 on 2020-11-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bussinesspage',
            fields=[
                ('bid', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.FileField(upload_to='')),
                ('source', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contactno', models.IntegerField()),
                ('rating', models.CharField(max_length=100)),
                ('listed', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('confirmpassword', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
    ]
