# Generated by Django 3.1.3 on 2020-11-28 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebookapp', '0002_bussinesspage_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bussinesspage',
            old_name='username',
            new_name='companyname',
        ),
    ]
